repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: git@github.com-emu:melisource/fury_websec-git-hooks
    rev: v2.0.0
    hooks:
      - id: pre_commit_hook
        stages: [ commit ]
      - id: post_commit_hook
        stages: [ post-commit ]

  # Datasec hook is MANDATORY, DO NOT comment it.
  - repo: git@github.com-emu:melisource/fury_datasec-git-hooks
    rev: 1.2.2
    hooks:
      - id: pre_commit_hook
        stages: [ commit ]
        verbose: true
      - id: post_commit_hook
        stages: [ post-commit ]